#!/bin/bash

basedir=$(dirname $0)
. $basedir/install.conf

function init(){
    mkdir -p $repositories
	mkdir -p $server
}

function update(){
    echo "updating"
}

function clean(){
    rm -rf $repositories
    rm -rf $server
}


while [ "$1" != "" ]; do
    case $1 in
		-i | --init )           init
		                        exit
                                ;;
        -u | --update )         update
                                exit
                                ;;
		-c | --clean )          clean
        						exit
                                ;;
        -h | --help )           help
                                exit
                                ;;
        *)                      help
                                exit
    esac
    shift
done



echo "done"