#!/bin/bash

scriptpath=$(readlink -f $0)
basedir=$(dirname ${scriptpath})
repoconf=$basedir/repositories.list
. $basedir/install.conf

echo $basedir
echo $repolist

function git_clone(){
    git clone $1
}

function git_update(){
    cd $1
    git reset --hard HEAD
	git clean -f -d
	git pull
	cd ..
}


function init(){
    . $repoconf
    cd $repositories
    for repository in ${repository_conf[@]}; do
        a=`eval "echo \$$repository`
	    echo git clone ${a[@]}
    done
    cd ..
}

function update(){
 echo "updating"

}

function clean(){
    echo "housekeeping"
    rm -rf $repositories/*
}

while [ "$1" != "" ]; do
    case $1 in
		-i | --init )           init
		                        exit
                                ;;
        -u | --update )         update
                                exit
                                ;;
		-c | --clean )          clean
        						exit
                                ;;
        -h | --help )           help
                                exit
                                ;;
        *)                      help
                                exit
    esac
    shift
done